Don't build Docker twice

diff --git a/.github/workflows/docker.yaml b/.github/workflows/docker.yaml
--- a/.github/workflows/docker.yaml
+++ b/.github/workflows/docker.yaml
@@ -123,18 +123,6 @@ jobs:
         with:
           ssh-private-key: ${{ secrets.ssh_private_keys }}
 
-      - name: Configure Docker build args
-        id: docker_args
-        env:
-          SCOPE: ${{ runner.os }}-${{ runner.arch }}-${{ inputs.cache_tag }}-${{ hashFiles(inputs.file) }}
-        run: |
-          echo "::set-output name=cache_from::type=gha,scope=$SCOPE"
-          echo "::set-output name=cache_to::type=gha,scope=${SCOPE},mode=max"
-
-          if [[ -n "$SSH_AUTH_SOCK" ]]; then
-            echo "::set-output name=ssh::default=$SSH_AUTH_SOCK"
-          fi
-
       - name: Save Git and SSH config
         run: |
           if ${{ steps.ssh.outputs.use != null }}; then
@@ -162,6 +150,18 @@ jobs:
           images: ${{ inputs.registry }}/${{ inputs.image_name || github.repository }}
           tags: ${{ env.TAGS }}
 
+      - name: Configure Docker build args
+        id: docker_args
+        env:
+          SCOPE: ${{ runner.os }}-${{ runner.arch }}-${{ inputs.cache_tag }}-${{ hashFiles(inputs.file) }}
+        run: |
+          echo "::set-output name=cache_from::type=gha,scope=$SCOPE"
+          echo "::set-output name=cache_to::type=gha,scope=${SCOPE},mode=max"
+
+          if [[ -n "$SSH_AUTH_SOCK" ]]; then
+            echo "::set-output name=ssh::default=$SSH_AUTH_SOCK"
+          fi
+
       - name: Build Docker image
         id: docker
         uses: docker/build-push-action@v2
@@ -175,32 +175,21 @@ jobs:
           cache-from: ${{ steps.docker_args.outputs.cache_from }}
           cache-to: ${{ steps.docker_args.outputs.cache_to }}
           load: true
-          tags: ${{ steps.meta.outputs.tags }}
+          tags: |
+            ${{ github.sha }}
+            ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
           target: ${{ inputs.target }}
-
-      - name: Save Docker image archive
-        id: image
-        env:
-          TAGS: ${{ fromJSON(steps.docker.outputs.metadata)['image.name'] }}
-          SHA: ${{ github.sha }}
-        run: |
-          IFS=$', ' command eval 'TAGS=($TAGS)'
-          TAG="${TAGS[0]}"
-          docker tag "$TAG" "$SHA"
-          docker save "$TAG" -o "${SHA}.tar"
-          echo "::set-output name=archive::${SHA}.tar"
-          echo "::set-output name=sha::$SHA"
 
       - name: Run startup tests
         if: inputs.startup_test
         env:
           FILE: ${{ inputs.startup_compose_file }}
           IMAGE_ENV_NAME: ${{ inputs.startup_image_env_name }}
-          BUILT_TAG: ${{ steps.image.outputs.sha }}
+          IMAGE_NAME: ${{ github.sha }}
         run: |
           if [[ -n "$IMAGE_ENV_NAME" ]]; then
-            eval "export ${IMAGE_ENV_NAME}=$BUILT_TAG"
+            eval "export ${IMAGE_ENV_NAME}=$IMAGE_NAME"
           fi
 
           echo '::group::docker compose up'
@@ -220,25 +209,27 @@ jobs:
           exit $EXIT_CODE
 
       - name: Scan for vulnerabilities with Trivy
-        uses: aquasecurity/trivy-action@master
-        with:
-          input: ${{ steps.image.outputs.archive }}
-          format: table
-          output: trivy-results.txt
-
-      - name: Inspect Trivy results
         env:
-          FILE: trivy-results.txt
+          IMAGE_REF: ${{ github.sha }}
           MATRIX: ${{ inputs.matrix }}
         run: |
-          echo '::group::Trivy results'
-          cat "$FILE"
+          echo '::group::docker pull bitnami/trivy'
+          docker pull bitnami/trivy
           echo '::endgroup::'
 
-          if [[ -s "$FILE" ]]; then
+          echo '::group::Trivy'
+          set +e
+          docker run --rm --user root \
+            --volume /var/run/docker.sock:/var/run/docker.sock \
+            bitnami/trivy image --exit-code 1 "$IMAGE_REF"
+          TRIVY_STATUS=$?
+          set -e
+          echo '::endgroup::'
+
+          if [[ $TRIVY_STATUS != 0 ]]; then
             PREFIX=`echo "$MATRIX" | jq -r '[. | to_entries | .[].value] | join(" / ")'`
             if [[ -n "$PREFIX" ]]; then PREFIX="${PREFIX/%/ / }"; fi
-            echo "::warning file=${{ inputs.file }},title=${PREFIX}Trivy::Vulnerabilities found"
+            echo "::warning file=${{ inputs.file }},title=${PREFIX}Trivy::Vulnerabilities found, please review logs"
           fi
 
       # TODO(jacob): Integrate Trivy with GitHub Security
@@ -251,19 +242,26 @@ jobs:
       # TODO(jacob): Configure Dockle lint
       - name: Lint with Dockle
         env:
-          INPUT: ${{ steps.image.outputs.archive }}
+          IMAGE_REF: ${{ github.sha }}
           MATRIX: ${{ inputs.matrix }}
         run: |
+          echo '::group::docker pull goodwithtech/dockle'
+          docker pull goodwithtech/dockle
+          echo '::endgroup::'
+
           echo '::group::Dockle'
-          if ! docker run --rm --volume "$PWD/$INPUT:/tmp/$INPUT" \
-            goodwithtech/dockle:latest --exit-code 1 --input "/tmp/$INPUT"
-          then
-            echo '::endgroup::'
+          set +e
+          docker run --rm --user root \
+            --volume /var/run/docker.sock:/var/run/docker.sock \
+            goodwithtech/dockle --timeout 10m --exit-code 1 "$IMAGE_REF"
+          DOCKLE_STATUS=$?
+          set -e
+          echo '::endgroup::'
+
+          if [[ $DOCKLE_STATUS != 0 ]]; then
             PREFIX=`echo "$MATRIX" | jq -r '[. | to_entries | .[].value] | join(" / ")'`
             if [[ -n "$PREFIX" ]]; then PREFIX="${PREFIX/%/ / }"; fi
-            echo "::warning file=${{ inputs.file }},title=${PREFIX}Dockle::Lint errors"
-          else
-            echo '::endgroup::'
+            echo "::warning file=${{ inputs.file }},title=${PREFIX}Dockle::Lint errors, please review logs"
           fi
 
       - name: Log into Docker registry
@@ -274,21 +272,17 @@ jobs:
           username: ${{ inputs.registry_username || github.actor }}
           password: ${{ secrets.registry_password || github.token }}
 
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v2
-        with:
-          file: ${{ inputs.file }}
-          context: ${{ inputs.context }}
-          build-args: |
-            ${{ secrets.build_args }}
-            ${{ inputs.build_args }}
-          ssh: ${{ steps.docker_args.outputs.ssh }}
-          cache-from: ${{ steps.docker_args.outputs.cache_from }}
-          cache-to: ${{ steps.docker_args.outputs.cache_to }}
-          push: ${{ inputs.push }}
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
-          target: ${{ inputs.target }}
+      - name: Push Docker image
+        if: inputs.push
+        env:
+          TAGS: ${{ steps.meta.outputs.tags }}
+        run: |
+          IFS=$'\n ' command eval 'TAGS=($TAGS)'
+          for TAG in "${TAGS[@]}"; do
+            echo "::group::push $TAG"
+            docker push "$TAG"
+            echo '::endgroup::'
+          done
 
       - name: Create multiarch manifest
         id: manifest
@@ -297,13 +291,13 @@ jobs:
           ARCHS: ${{ inputs.archs }}
           BASE_TAGS: ${{ inputs.tags }}
           BASE_MANIFEST: ${{ inputs.registry }}/${{ inputs.image_name || github.repository }}
-          BUILT_TAGS: ${{ fromJSON(steps.docker.outputs.metadata)['image.name'] }}
+          BUILT_TAGS: ${{ steps.meta.outputs.tags }}
         run: |
           IFS=$'\n ' command eval 'ARCHS=($ARCHS)'
           IFS=$'\n ' command eval 'BASE_TAGS=($BASE_TAGS)'
           BASE_MANIFEST="${BASE_MANIFEST,,}"
 
-          IFS=', ' command eval 'BUILT_TAGS=($BUILT_TAGS)'
+          IFS='\n ' command eval 'BUILT_TAGS=($BUILT_TAGS)'
           BUILT_TAGS="^($(IFS=\|; echo "${BUILT_TAGS[*]}"))$"
 
           MANIFESTS=()
